### ISSUE TITLE
add image description and contribution

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/cabinetofcuriosity_site#5]
We need to incorporate image attribution and image description for each image. Ideally this would be in the form of a css tag we could add to each image tag or something equivalent. It would be great as an images description below (small type) the image with a link to the source of the image.

**Comment by iamciera** [comment]
For example, I just ended up adding descriptive text to the image in [this post](http://curiositydata.org/assets/img/2018-05-17-digital_data_in_copenhagen/): [exmple image](http://curiositydata.org/assets/img/2018-05-17-digital_data_in_copenhagen/images-04.jpg). This is the *wrong* way to do it, but looks like how I would want the description, but with smaller text.

**Comment by DarkoArnautov** [comment]
Fixed in commit c720550.
You can use following code in markdown content.
{% include image.html url="" description="" %}

e.g.
{% include image.html url="../assets/img/2018-05-17-digital_data_in_copenhagen/images-03.jpg" description="Front entrance to the greenhouses at the Natural History Museum of Denmark Botanical Gardens, Copenhagen." %}
